# Generated by Django 2.2.14 on 2021-02-20 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Champagne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=25, verbose_name='Brand')),
                ('color', models.CharField(max_length=25, verbose_name='Color')),
                ('size', models.CharField(max_length=25, verbose_name='Size')),
                ('champ_type', models.IntegerField(choices=[(4, 'Demi-Sec'), (1, 'Brut'), (3, 'Dry'), (5, 'Doux'), (2, 'Extra Dry')], verbose_name='Champagne Type')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
        ),
    ]
