# Generated by Django 2.2.14 on 2021-02-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champagne', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champagne',
            name='champ_type',
            field=models.IntegerField(choices=[(5, 'Doux'), (3, 'Dry'), (1, 'Brut'), (4, 'Demi-Sec'), (2, 'Extra Dry')], verbose_name='Champagne Type'),
        ),
    ]
