# Generated by Django 2.2.14 on 2021-02-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champagne', '0003_auto_20210220_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champagne',
            name='champ_type',
            field=models.IntegerField(choices=[(5, 'Doux'), (2, 'Extra Dry'), (4, 'Demi-Sec'), (1, 'Brut'), (3, 'Dry')], verbose_name='Champagne Type'),
        ),
    ]
